import { Hono } from "hono";
import { zValidator } from "@hono/zod-validator";
import { z } from "zod";
import * as fs from "fs/promises";
import * as path from "path";
import type { AppEnv } from "../types.js";

export const reviewRoutes = new Hono<AppEnv>();

// Zod schema for the expected review payload
const reviewSchema = z.object({
  step1: z.string().optional(), // Clear the Deck
  step2: z.string().optional(), // Reflect
  step3: z.string().optional(), // Plan / Goals
});

/**
 * POST /api/reviews
 * Creates a physical markdown file on the local filesystem.
 */
reviewRoutes.post(
  "/",
  zValidator("json", reviewSchema),
  async (c) => {
    try {
      const body = c.req.valid("json");
      const userId = c.get("userId");

      if (!userId) {
        return c.json({ error: "Unauthorized" }, 401);
      }

      const now = new Date();
      const monthPrefix = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
      
      // We will place everything in the `/app/reviews/{userId}/{YYYY-MM}` folder
      const dirPath = path.join("/app", "reviews", userId, monthPrefix);
      await fs.mkdir(dirPath, { recursive: true });

      // Count existing files to determine "week-X"
      const existing = await fs.readdir(dirPath);
      const mdFiles = existing.filter(f => f.endsWith(".md") && f.startsWith("week-"));
      const nextWeekNum = mdFiles.length + 1;
      const fileName = `week-${nextWeekNum}.md`;

      const filePath = path.join(dirPath, fileName);

      // Build the Markdown content
      const dateString = now.toLocaleDateString("en-US", { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
      const mdContent = `# Weekly Review - ${dateString}

## 1. Clear the Deck
${body.step1?.trim() || "_No specific notes left._"}

## 2. Reflection & Learnings
${body.step2?.trim() || "_No reflection left._"}

## 3. Goals & Planning
${body.step3?.trim() || "_No goals recorded._"}

---
*Automatically generated by DevPlanner*
`;

      await fs.writeFile(filePath, mdContent, "utf-8");

      return c.json({ success: true, file: filePath });
    } catch (e) {
      console.error("[Review Route Error]", e);
      return c.json({ error: String(e) }, 500);
    }
  }
);
